<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-KanbanTaskManagement-5514a59c-a0a0-4a28-81bb-5461196cea59</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Markdown" Version="2.2.1" />
    <PackageReference Include="MongoDB.Driver" Version="3.8.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\" />
  </ItemGroup>

</Project>
